name: Infrastructure deployment
on: [
  workflow_dispatch
]

permissions:
    id-token: write
    contents: read

jobs:
  validate-bicep:
    runs-on: ubuntu-latest
    steps:
      # Checkout code
    - uses: actions/checkout@main

      # Install Bicep CLI
    - name: Install Bicep CLI
      run: |
        az bicep install

      # Validate Bicep files
    - name: Validate Bicep files
      run: |
        az bicep build --file ./infrastructure/main.bicep

      # Lint Bicep files
    - name: Lint Bicep files
      run: |
        bicep lint ./infrastructure/main.bicep

  deploy-infrastructure:
    runs-on: ubuntu-latest
    environment: Production
    needs: validate-bicep
    steps:

      # Checkout code
    - uses: actions/checkout@main

      # Log into Azure
    - name: Login to Azure
      uses: azure/login@v2
      with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      # Deploy Bicep file
    - name: Deploy bicep to Azure
      uses: Azure/cli@v2
      with:
        inlineScript: |
          az config set bicep.use_binary_from_path=False
          az deployment sub create \
          --location westeurope \
          --template-file ./infrastructure/main.bicep \
